services: 
  app:
    build: 
      context: .
      dockerfile: deploy/python/Dockerfile
    environment:
      DB_USER: django
      DB_PASSWORD: django
      DB_NAME: django
      DB_HOST: db
    ports:
      - 8000:8000

  db:
    image: postgres:14-alpine
    # ports:
    #   - 5432:5432
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_USER: django
      POSTGRES_DB: django
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: