version: '3'

services:
  nginx:
    image: docker-nginx:latest
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static:/app/static
    depends_on:
      - app

  app:
    image: docker-django:latest
    build: 
      context: .
      dockerfile: deploy/python/Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - django-db
    environment:
      DB_HOST: django-db 
    volumes:
      - static:/app/static

  django-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

volumes:
  static: